app:
  name: TuneGraph

data:
  limited: true

# Model hyperparameters
model:
  embedding_dim: 64
  num_layers: 3
  num_intents: 4   # DGCF disentangled factors
  reg_weight: 1e-4

# Training settings
train:
  batch_size: 1024
  lr: 1e-4
  epochs: 50
  eval_every: 1
  num_workers: 12