app:
  name: TuneGraph

data:
  mpd_json: "/path/to/million-playlist-dataset/playlist.json"
  output_dir: "./data/processed"

# Model hyperparameters
model:
  embedding_dim: 64
  num_layers: 3
  num_factors: 4   # DGCF disentangled factors
  reg_weight: 1e-4

# Training settings
train:
  batch_size: 1024
  lr: 1e-4
  epochs: 50
  eval_every: 1